export {default as Layout} from './Layout/Layout.jsx'
export {default as Welcome} from './Welcome/Welcome.jsx'
export {default as ProtectedRoute} from './ProtectedRoute/ProtectedRoute.jsx'
export {default as Login} from './Login/Login.jsx'
export {default as Register} from './Register/Register.jsx'
export {default as SignUpFormTwo} from './Register/SignUpFormTwo.jsx'
export {default as SignUpFormThree} from './Register/SignUpFormThree.jsx'
export {default as SignUpFormFour} from './Register/SignUpFormFour.jsx'